{{- range $.Values.env.tenants }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Values.env.name }}-{{ $.Values.app.name }}-{{ . }}-api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{ $.Values.env.name }}-{{ $.Values.app.name }}-{{ . }}-api
  ports:
    - port: 80
      targetPort: 80
---
{{- end}}