apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend
    template:
        metadata:
            labels:
                component: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend
        spec:
            containers:
                -   name: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend
                    image: "mmalujdy/car-dealership-frontend:{{ .Values.deployment.frontendTag }}"
                    ports:
                        -   containerPort: 3000
                    env:
                        - name: NODE_ENV
                          value: {{ .Values.env.name }}