apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend
  ports:
    - port: 80
      targetPort: 80