apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
    name: {{ .Values.env.name }}-{{ .Values.app.name }}-ingress-service-non-rewrite
    annotations:
        ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/ssl-redirect: "false"
        nginx.ingress.kubernetes.io/use-regex: "true"
spec:
    rules:
        -   http:
                paths:
                    -   path: /(.*).(js|css|json|png|ico|svg)
                        pathType: Prefix
                        backend:
                            service:
                                name: {{ .Values.env.name }}-{{ .Values.app.name }}-frontend-cluster-ip-service
                                port:
                                    number: 80
                    {{- range $.Values.env.tenants }}
                    -   path: /{{ . }}/api(.*)
                        pathType: Prefix
                        backend:
                            service:
                                name: {{ $.Values.env.name }}-{{ $.Values.app.name }}-{{ . }}-api-cluster-ip-service
                                port:
                                    number: 80
                    {{- end}}
    ingressClassName: nginx