apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
#    kubernetes.io/ingress.class: azure/application-gateway
    ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
    - http:
        paths:
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env.name }}-{{ .Values.app.name }}-{{ .Values.env.tenant }}-api-cluster-ip-service
                port:
                  number: 80
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Values.env.name }}-{{ .Values.app.name }}-{{ .Values.env.tenant }}-frontend-cluster-ip-service
                port:
                  number: 80
  ingressClassName: nginx