apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver
  template:
    metadata:
      labels:
        component: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver
    spec:
      containers:
        - name: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver
          image: mcr.microsoft.com/mssql/server:2019-CU15-ubuntu-20.04
          ports:
            - containerPort: 1433
          env:
            - name: ACCEPT_EULA
              value: "Y"
            - name: SA_PASSWORD
              value: "1Secure*Password1"