apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.env.name }}-{{ .Values.app.name }}-sqlserver
  ports:
    - port: 1433
      targetPort: 1433