apiVersion: apps/v1
kind: Deployment
metadata:
    name: api-deployment
spec:
    replicas: 1
    selector:
        matchLabels:
            component: api
    template:
        metadata:
            labels:
                component: api
        spec:
            containers:
                -   name: api
                    image: "mmalujdy/car-dealership-api:{{ .Values.deployment.backend.tag }}"
                    ports:
                        -   containerPort: 80
                    env:
                        - name: ASPNETCORE_URLS
                          value: "http://+:80"
                        - name: ASPNETCORE_ENVIRONMENT
                          value: "Production"
                        - name: CAR_DEALERSHIP_CURRENT_TENANT
                          value: {{ .Values.env.tenant }}
