apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.env.name }}-{{ .Values.app.name }}-{{ .Values.env.tenant }}-api-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: {{ .Values.env.name }}-{{ .Values.app.name }}-{{ .Values.env.tenant }}-api
  ports:
    - port: 80
      targetPort: 80